openapi: 3.0.0
info:
  title: Event Booking API
  version: 1.0.0
  description: API for managing events and bookings

servers:
  - url: http://localhost:3000

paths:

  /events:
    get:
      summary: Get all events
      responses:
        '200':
          description: List of events

    post:
      summary: Create event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                total_capacity:
                  type: integer
      responses:
        '201':
          description: Event created

  /bookings:
    post:
      summary: Create booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                event_id:
                  type: integer
      responses:
        '201':
          description: Booking successful

  /users/{id}/bookings:
    get:
      summary: Get bookings for a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of bookings

  /events/{id}/attendance:
    post:
      summary: Validate booking using booking code
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                booking_code:
                  type: string
      responses:
        '200':
          description: Valid booking